### ISSUE TITLE
"Create New Incident" and "Manage" buttons have disappeared

### ISSUE THREAD

**Issue by tcrobbins4** [OfficeDev/microsoft-teams-emergency-operations-center#146]
Buttons are missing in all desktop apps and web version of Teams.   I restarted the App Services associated and that didn't help.  Also, not really sure what the best way to "RESET" everything is if you can also tag that answer onto this issue.

![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/32391514/3b6250cc-a1c7-4e09-a148-62b51989fb5d)

**Comment by v-asshrirao** [comment]
@tcrobbins4, Thank you for reaching out to us.
It looks like Admin enabled Role based setting in the App which is why "Create New Incident" and "Manage" buttons are not visible to you. 
<img width="376" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/04dc7f51-3938-4f0e-b13b-35908fd3f170">

Can you please check with Admin and confirm.

**Comment by tcrobbins4** [comment]
Ok.  So I'm the admin and I turned on Roles to see how it worked.  I figured out how to assign a role in the UserRoles list.  The only role listed there is Admin.  What other roles are there to be used?  I don't see anything in any documentation referencing how the Roles work.  Thanks.

**Comment by tcrobbins4** [comment]
I was able to find a statement that explains how the singular admin role works.
