### ISSUE TITLE
App Deployment Update Client Secret

### ISSUE THREAD

**Issue by boaras** [OfficeDev/microsoft-teams-emergency-operations-center#147]
On deployment step 3, I accidentally copied the Client Secret ID and not the Client Secret Value. How do I update the value in my Azure deployment? I would also like to suggest that this gets added to the Wiki Troubleshooting section, or FAQ.

**Comment by v-asshrirao** [comment]
@boaras, Thank you for reporting this.
For updating the client secret value, navigate to simpleAuthAppService which got created during deployment.
Navigate to environment variables, and update the CLIENT_SECRET value.
Once value is updated, restart the simpleAuthAppService.
<img width="535" alt="image" src="https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/f92ca165-decc-4aac-84e6-2ad4c7e36dad">

Please do let us know if this helps.
Thank you for your suggestion, we will try to update this steps in wiki troubleshooting section in our future release.

**Comment by boaras** [comment]
Thank you for the response! I updated the value but still receive a blank screen in Teams, as well as SharePoint.

**Comment by v-asshrirao** [comment]
@boaras, Can you please open TEOC app in web version of teams and share console logs and network logs with us.
Also, can you please confirm if deployment was successful and SharePoint site is created successfully.

**Comment by boaras** [comment]
[teams.microsoft.com-1698845031214.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/13227474/teams.microsoft.com-1698845031214.log)
![SharePointSite](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/20359954/fe0edc48-a573-4d9f-a84a-e11646d9a1eb)
I attached the log and a screenshot to show that the site was created. No errors during deployment.

**Comment by v-asshrirao** [comment]
@boaras , Can you please confirm if you have tried to add the TEOC app in teams, if yes, can you let us know if you are getting any error in that App.

The logs you have shared don't have the information related to TEOC App.

To generate the logs, open TEOC app in web version of teams and try to reproduce the error and share the logs generated in console, also please share network trace so that we can help you with the issue.

**Comment by boaras** [comment]
I have attached the log again, from Teams Online. I might need some instructions on how to get you the Network Trace. I tried to export the Network tab data but it is too large to upload here.

[teams.microsoft.com-1698936936737.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/13241266/teams.microsoft.com-1698936936737.log)
![TeamsOnline](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/20359954/c2838ed6-be50-438c-9d2e-e2e559d1dbeb)
![TeamsClient](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/20359954/c23435a9-1193-423d-a484-def499a884eb)

**Comment by v-asshrirao** [comment]
@boaras, The TEOC app itself is not coming and the errors don't have any information related to what is not working.

Can you please share few details with screenshot to understand this better.

1. Please Navigate to Resource Group, in overview section you can find the deployment details and share the below screenshot,
![image](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/assets/141898119/dec93260-b95f-411c-a1ea-360be2174782)
2. Navigate to SharePoint Site which you have provisioned and confirm if its loading.
3. Share the manifest files so that we can verify them
