### ISSUE TITLE
Customization Help

### ISSUE THREAD

**Issue by idavis162** [OfficeDev/microsoft-teams-emergency-operations-center#202]
I am wanting to change the variables for severity. I am not to sure where to change that. And after changing a field, do I have to re provision the site? Or just redeploy the app?

**Comment by v-ajaysahu** [comment]
@idavis162 , Thank you for reporting this.
We do not support any customization and if you customize the solution according to your organization needs, there are chances that you might face challenges while upgrading to new versions with the future releases.
If you want to still customize or update Severity value, then you need you need to update Constant file and you might have to test the app since Severity value is used in multiple places. If you've existing Incidents before your changes has been applied, you might have to provision the site as well.
