### ISSUE TITLE
Bing Maps vs Azure Maps Key

### ISSUE THREAD

**Issue by ORNC** [OfficeDev/microsoft-teams-emergency-operations-center#238]
We don't have a bing maps key and now that's been deprecated are we waiting for an app update to use an Azure Maps key with this app?

**Comment by v-saikirang** [comment]
Hi @ORNC,
Thanks for reaching out to us. We have not yet looked in to the integration of Azure Maps Key instead of bing maps key. But we have it on our backlog. We will assess and try to prioritize in one of our future releases.

But as per feedback from another user the Azure Maps is also working with certain limitations. You can reefer to this [issue](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/issues/230).

For now i am closing this ticket. Please let us know if you need additional information.

Thanks.
