### ISSUE TITLE
Blank welcome screen, No incident buttons or any data on TEOC solution app

### ISSUE THREAD

**Issue by poojarajput55** [OfficeDev/microsoft-teams-emergency-operations-center#247]
![TEOC](https://github.com/user-attachments/assets/f37a2410-b107-483f-aeab-62d61926556a)

TEOC interface in Teams is missing Manage and New Incident buttons. The user account I am logged into with is an owner on the TEOC App in Azure

**Comment by SemBurendo** [comment]
@poojarajput55 check app insights to see if the website graph api calls are failing

**Comment by v-saikirang** [comment]
Hi @poojarajput55,

Thanks for reaching out to us.

Can you please share a screenshot of the site contents page of the Share point site you created and also confirm if you have provided permissions in the Member group of the SP site.

Thanks,
Sai.

**Comment by v-ajaysahu** [comment]
@poojarajput55 , 
Following our conversation, here are the steps you should take to resolve your issue:

1. Create a new client secret because the previous one was copied incorrectly. Make sure to copy its value.
2. Retrieve and copy the Tenant Id from the App registration.
3. Before deleting the existing resource group, remember to copy its name and the base resource. This way, you won't have to redeploy to the Teams Admin center.
4. Refer to step 3 in the deployment guideline.
5. Enter the correct values and proceed with the deployment.

For your convenience, here's the direct link to step 3: https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-deploy-to-your-azure-subscription
