### ISSUE TITLE
Not able to create incidents

### ISSUE THREAD

**Issue by gsalcedo23** [OfficeDev/microsoft-teams-emergency-operations-center#260]
I deployed my TEOC Teams app, and it's not allowing me to create new incidents; it just keeps trying to load onto the next screen with no result. Does anyone have a fix or ideas on how to fix this?

 see screenshot below
![2024-09-26_7-38-49](https://github.com/user-attachments/assets/bc41921c-f51d-4a83-a000-7809bdc831fe)
![TEOC1](https://github.com/user-attachments/assets/58134378-f417-4044-83e4-2ee3d9836244)

**Comment by v-ajaysahu** [comment]
@gsalcedo23, thank you for notifying us. 
Please launch Microsoft Teams via a web browser, activate the developer tool, and keep it open. Next, initiate the TEOC application and attempt to replicate the issue. Afterwards, share the console logs and network traces with us for troubleshooting purposes.

**Comment by gsalcedo23** [comment]
![console logs](https://github.com/user-attachments/assets/4f93f1da-df50-4580-920f-32c62f8bfa22)
![network pic](https://github.com/user-attachments/assets/e6df2999-8992-4fda-acd2-4982b5628b52)
hello these are the logs you requested, thanks for your help

**Comment by v-ajaysahu** [comment]
@gsalcedo23 ,
Based on the screenshot, it appears that some lists might be missing or have been renamed. To assist with troubleshooting, could you please share the log files instead of the screenshot? 
Below are the SharePoint lists which TEOC app connects with -

- TEOC-IncidentStatus
- TEOC-IncidentType
- TEOC-RoleAssignments
- TEOC-IncidentTransaction
- TEOC-Assessments
