### ISSUE TITLE
Unable to run TEOC solution and still facing the same issue

### ISSUE THREAD

**Issue by poojarajput55** [OfficeDev/microsoft-teams-emergency-operations-center#264]
![TEOC app blank screen](https://github.com/user-attachments/assets/659f29d9-03f9-4fe6-83d9-d8e0ec891a78)

Hi @v-ajaysahu,

As discussed we are still facing the same issue while accessing the TEOC solution and still see a blank screen, Could you please have a look.

**Comment by v-ajaysahu** [comment]
@poojarajput55 , thanks for reporting issue.
As discussed, please share the console logs and network traces directly here in GitHub so that we can troubleshoot this issue.

**Comment by bennyhoffj** [comment]
We are also getting this same error upon login with a blank screen other than name. Looking at network trace (f12) in edge using the teams browser I am getting a 400 error.  The url i cant hit is something like %baseapp%/sites/sharepointsiteurl.   

how can i share har file for review.

also of note: during deployment guide I cant find “accessTokenAcceptedVersion” in the manifest. So I could not find a way to update this from Null to 2.

**Comment by v-ajaysahu** [comment]
@bennyhoffj ,
Your problem seems to be distinct from the one discussed. Typically, the error you're encountering arises from either capitalizing the Base resource name or using the full SharePoint URL instead of just the endpoint. For instance, if your TEOC site URL is 'https://example.sharepoint.com/sites/TEOCSite', you should enter 'TEOCSite' alone, not the full URL. To confirm this, please go to the Azure Resource group, select "Microsoft.template", and review your inputs. Should the problem continue, consider creating an issue for further assistance.

**Comment by bennyhoffj** [comment]
Reviewed the input and we did have the full URL. Redeployed the application with the correct convention. However, we are experiencing the exact same problem.

F12 in edge gets a 400 status to  https://xxxxx.azurewebsites.net/sites/xxx.sharepoint.com:/sites/xxx.sharepoint.com/sites/xxxxx?$select=id

**Comment by v-ajaysahu** [comment]
@poojarajput55 ,
We've successfully addressed your issue in the recent meeting. The problem arose because the Client ID: 5e3ce6c0-2b1f-4285-8d4b-75ee78787346 (Teams WebApp Client Id) wasn't added under 'Expose an API' in the App Registration. Additionally, the site was manually created with a prefix of https://example.sharepoint.com/teams/TEOCSite instead of the correct https://example.sharepoint.com/sites/TEOCSite. Now that these steps have been corrected, your issue has been resolved, and we'll be closing it. If you have any further questions, feel free to post them here.
