### ISSUE TITLE
Deployment Slots

### ISSUE THREAD

**Issue by BCG-cmori** [OfficeDev/microsoft-teams-emergency-operations-center#271]
Hi - I wanted to see if its possible to use Azure Deployment Slots so that I can have a staging environment and a production environment of EOC so that I can perform upgrades and performing testing before I deploy an upgrade to my users and so that they won't experience any downtime. Since this will be using in emergency situations we wouldn't want this going down during an emergency. 

If you have any other recommendations that would be great. 

Is there a way to browse to EOC just within the browser outside of Teams/Teams Webapp to perform testing and validation on the staging environment?

**Comment by BCG-cmori** [comment]
Would it be best to just add a "staging" app to Teams with the updated links?

**Comment by v-ajaysahu** [comment]
@BCG-cmori , thanks for bringing this to our attention.
Upgrading the system should not result in any downtime, provided that the upgrade documentation is followed correctly. It's generally not recommended to run multiple instances of the TEOC app within a single tenant due to the use of the Teams app ID in our code, which enables the display of the Active Dashboard in the General channel. If you decide to deploy multiple TEOC apps, it's possible by modifying the Manifest for one of the environments. However, we advise against making changes to the Production environment and suggest maintaining separate Azure Resource groups for each instance. Please note, in the environment where the Manifest has been altered, the Active Dashboard will not function as it requires the Teams App ID to be updated.
Additionally, this app is designed to operate exclusively within the Teams app environment.
I hope this addresses your concerns.
