### ISSUE TITLE
Please Wait screen

### ISSUE THREAD

**Issue by thatguy9129** [OfficeDev/microsoft-teams-emergency-operations-center#45]
Getting back to this after some time off. I successfully created a new incident but the system just sits on the Please Wait... screen. If I refresh the page, the new incident will show but if I try to edit the incident or interact with it in any way, I get the Please Wait... screen again and I can not get past it. What information do you need to debug this issue? I have a HAR file but I don't want to post it here if that helps. Just to troubleshoot, I added more resources to the app service but that did not help.

I am running version 0.5.1 (current).

**Comment by v-prigunasek** [comment]
Hi @thatguy9129 ,

Thanks for reporting the issue here. Yes, please share us the log file to troubleshoot on this issue.

**Comment by thatguy9129** [comment]
> Hi @thatguy9129 ,
> 
> Thanks for reporting the issue here. Yes, please share us the log file to troubleshoot on this issue.

Do you have a private location I can upload it to?

**Comment by v-prigunasek** [comment]
yes, you can [email](mailto:v-prigunasek@microsoft.com) me if that works for you. Thanks

**Comment by v-prigunasek** [comment]
Hi Bryan,
Thanks for your time over the call. We noticed some issues with the old incidents, that might be because the process would have been interrupted during the incident creation. Since those items were missing some values in the list, you were unable to update those incidents. 

We created few new incidents after clearing the old items and everything was working as expected. Hence closing the ticket.

Thanks!
