### ISSUE TITLE
Login successful but no dashboard appears

### ISSUE THREAD

**Issue by kilianb-cosp** [OfficeDev/microsoft-teams-emergency-operations-center#58]
No errors on deployment.  Added app to Teams.  Able to login, but no dashboard appears.  SharePoint permissions assigned.
![SuccessfulLogin](https://user-images.githubusercontent.com/117785358/200702973-b1849f55-f57d-4f60-a1ce-c8004df18318.png)

Here is a Fiddler trace when the Teams TEOC tab is reloaded:

![Fiddler-ReloadTabInTeams](https://user-images.githubusercontent.com/117785358/200703075-dfdf0138-8c86-4443-b30b-cdb5446c458a.png)

**Comment by v-prigunasek** [comment]
Hi @kilianb-cosp,

Thanks for reaching out to us. Can you please confirm whether you are able to access the SharePoint site?
https://xxx.sharepoint.com/sites/TeamsEOCSite

I believe, you have provided the same SharePoint site name while creating the [resource group](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/wiki/Deployment-Guide#3-deploy-to-your-azure-subscription) which was provisioned in Step 1.

**Comment by sheacm** [comment]
I had the same experience when I first deployed this, in my case I accidentally entered the full URL for the SharePoint site in this field (shown below), rather than just the site name.  Based on your request header, it looks like you may have done the same.  I ended up completely deleting the App Service/Plan/Etc. and redeploying it using the exact same 'base resource name' and then it worked.
![image](https://user-images.githubusercontent.com/117464940/200854612-5420ccbe-1411-468e-b935-41a971ecda3d.png)

**Comment by kilianb-cosp** [comment]
I have resolved the issue.  I had assigned a baseResourceName which had a dash (-) in the name.  Updating the name, using all letters only, and re-deploying the app services in Azure, resulted in the dashboard appearing in the Teams client.  I was successful in creating a test incident.

Thank you to @sheacm for providing the insight.
