### ISSUE TITLE
When Launching TEOC from Teams or Teams Web header and Name show up but blank body

### ISSUE THREAD

**Issue by rsnyder-feld** [OfficeDev/microsoft-teams-emergency-operations-center#65]
[teams.microsoft.com-1672759470218.log](https://github.com/OfficeDev/microsoft-teams-emergency-operations-center/files/10337745/teams.microsoft.com-1672759470218.log)

Not sure what I did wrong worked well in the lab but in production getting what others have I tried redploying and going over the steps again.  attached is the console logs from my web teams session.

**Comment by v-prigunasek** [comment]
Hi @rsnyder-feld ,

Thanks for sharing the logs. I see the issue is with the SharePoint Site Name (/sites/feld_teoc) that was provided while creating a resource group.  Please update the REACT_APP_SHAREPOINT_SITE_NAME setting to **feld_teoc** in the resource group and try again.

To update the configuration, navigate to Azure Portal --> Resource group --> App service --> Configuration --> Edit the REACT_APP_SHAREPOINT_SITE_NAME setting --> Update the value to **feld_teoc** --> Click OK --> Click Save 

![image](https://user-images.githubusercontent.com/98514691/210395985-2fe58b01-052d-498a-9bc5-1b947352a712.png)

**Comment by rsnyder-feld** [comment]
I made the change and hit saved and the service restarted but even thought it just feld_teoc it still showing up wrong in the console.
![image](https://user-images.githubusercontent.com/115168361/210441524-86aa1c2e-2fed-4cd2-8fc3-1504b434ed84.png)

its only been like 5 minutes so I may not be being patient enough.

**Comment by v-prigunasek** [comment]
Hi @rsnyder-feld ,

Can you please sync the code again after updating the above-mentioned configuration?

1. In Azure portal, navigate to TEOC resource group, open app service and click on deployment center.
2. Click on sync.
3. Wait until you see status as success for sync.
4. Then try to launch the application in Teams again.

![image](https://user-images.githubusercontent.com/98514691/210476572-0913c8d6-4e74-4cd4-82e0-e1081fff95a6.png)
