### ISSUE TITLE
Welcome email notifications

### ISSUE THREAD

**Issue by sheacm** [OfficeDev/microsoft-teams-emergency-operations-center#69]
Hello -- We noticed that new Team members are not receiving an email notification when a new Team is created by way of the TEOC incident dashboard.  Normally, when users are added to a new Team (outside of TEOC) the member will receive a "You have been added..." message from noreply@email.teams.microsoft.com.  Is this by design or should this be working for us?

We were hoping that the email would serve as the notification to the user that there is a new incident.  If this doesn't happen, do you have any suggestions for how to notify a user via email that the new Team has been created?

Thanks,
Chris

**Comment by v-prigunasek** [comment]
Hi @sheacm ,

Thanks for reaching out to us.

Yes, this is by design as we are creating M365 group first and then adding a Team to it. If we create a Team directly from MS Teams we would be receiving that email notification as you have mentioned but for now in TEOC application, the only notification users would be getting is in the Activity feed in Teams when the incident is created.

We will further analyze on the email notifications and if it is something feasible for our design, we will try to add it as a feature in our next release.

**Comment by sheacm** [comment]
Thank you, email notifications would a valuable addition.
